```{r include = FALSE}
if(!knitr:::is_html_output())
{
  options("width"=56)
  knitr::opts_chunk$set(tidy.opts=list(width.cutoff=56, indent = 2), tidy = TRUE)
  knitr::opts_chunk$set(fig.pos = 'H')
}
```

# Introduction

This section of the book is aimed at those who are either complete beginners in data analysis and statistical computing or who have some prior experience with another language or software package and want to learn more about R.

Here, we'll take a look at the basics but without going into too much detail so as to be confusing. If you make it through this section, when you come out the other side you'll have more than enough knowledge to be able to complete your first real R project.

For those of you who feel you want to understand what underpins the concepts and code we're going to look at, or those who want to eventually teach R to others, the following section ("For Teachers") will go into more detail. For example, you'll need to understand what a function is to use R, but you won't need to know how to create one. In the "For Students" section, we look at what a function is, and then we learn how to create one in the "For Teachers" section.
